development:
  adapter: postgresql
  database: linear_regression_development
  user: root
  password:

test:
  adapter: postgresql
  database: linear_regression_test
  user: root
  password:

production:
  adapter: postgresql
  database: linear_regression_production
  user: root
  password:
